p(is_m = 1, m_diff = 10, letter = 'b', is_show = 0)
p(is_m = 1, m_diff = 10, letter = 'c', is_show = 0)
p(is_m = 1, m_diff = 10, letter = 'd', is_show = 0)
p(is_m = 1, m_diff = 10, letter = 'e', is_show = 0)
p(is_m = 1, m_diff = 10, letter = 'f', is_show = 0)
p(is_m = 1, m_diff = 10, letter = 'g', is_show = 0)
p(is_m = 1, m_diff = 10, letter = 'h', is_show = 0)
p(is_m = 1, m_diff = 10, letter = 'i', is_show = 0)
p(is_m = 1, m_diff = 10, letter = 'j', is_show = 0)
p(is_m = 1, m_diff = 10, letter = 'k', is_show = 0)

