#+TITLE: pyshemkf: Python environment for handling SHEMAT-Suite output of EnKF simulations
#+AUTHOR: Johannes Keller

=pyshemkf= (=py= thon environment for handling =shem= at-suite output
of en =kf= simulations) is a python environment for post-processing
SHEMAT-Suite ([[*Rath 2006][Rath 2006]]) output. It can help to generate 2D-figures of
variables and parameters. Most notably, =pyshemkf= contains scripts
and functions for the evaluation and visualization of RMSE
distributions from Ensemble Kalman Filter (EnKF, [[*Evensen 2003][Evensen 2003]])
synthetic experiments computed with SHEMAT-Suite.

-----
* Prerequisites
The scripts are written for =python2.7.12=. They make use of the
following Python modules:
- =matplotlib=, =matplotlib.pyplot=, =matplotlib.cm=,
  =matplotlib.colors=, =matplotlib.mlab= are used for plotting
- =numpy=, =scipy=, =scipy.stats= provide numerical and matrix
  functions
- =shutil=, =os=, =subprocess=, =shlex= are used to run commands on
  the operating system
- =string= provides string manipulation utilities
- =exceptions= is used for exception handling
- =vtk= and =h5py= provide functions to read vkt and hdf files.

For the included module =pskf= to be loaded Python, its path has to be
added to the environment variable =PYTHONPATH=:
#+BEGIN_SRC sh
  export PYTHONPATH=${PYTHONPATH}:<path_to>/pyshemkf/site-packages
#+END_SRC

* General information
Explanation of the =pyshemkf= directory structure followed by an
account of the naming convention for SHEMAT-Suite output directories
required for compatibility with =pyshemkf=.
** pyshemkf structure
There are three general directories in =pyshemkf=: One for output, one
for Python-scripts and one for the Python module pskf.
*** =output/=
Directory for output of all tags. There is one subdirectory for each
tag. Each of these subdirectories contains subdirectories of the form
=npy/=, =png/=, =pdf/= and =npy/= to save the corresponding
files. Additionally, the directories =dists= ([[output/dists/]] for RMSE
distributions) and =specs= ([[output/specs/]] for specifier function
related output) contain only numpy arrays in =npy/=.
*** =/scripts=
IPython scripts for reading and plotting SHEMAT-Suite output sorted by
a tag that signifies the specific use.
*** =/site-packages/pskf=
Module containing functions used by the IPython scripts of =pyshemkf=.
Some functions are meant to be specific to certain IPython scripts,
others are general functions used throughout =pyshemkf=.

For the module to be loaded by Python, its path has to be added to the
environment variable =PYTHONPATH= (see [[*Prerequisites][Prerequisites]]).
** SHEMAT-Suite output directory
=pyshemkf= needs a specific naming convention of SHEMAT-Suite output
directories. A single output directory should be named as follows:
#+BEGIN_SRC sh
  $HOME/shematOutputDir/<model_name>_output/<dat>/<dat>_<let>
#+END_SRC
An example with =<model_name>=wavereal=, =<dat>=2010_01_30=,
=<let>=a=:
#+BEGIN_SRC sh
  $HOME/shematOutputDir/wavereal_output/2010_01_30/2010_01_30_a
#+END_SRC
Inside the SHEMAT-Suite output directories, input files are saved
alongside output directories.

- Input files
  - general input file =<MODEL_NAME>= (=WAVEREAL=)
  - true input file =<MODEL_NAME>_TRUE= (=WAVEREAL_TRUE=)
  - EnKF input file =<MODEL_NAME>.enkf= (=WAVEREAL.enkf=)
  - SGSim input fiels =sgsim_k_<modelname>_true.par=
    (=sgsim_k_wavereal_true=), =sgsim_k_<modelname>.par=
    (=sgsim_k_wavereal=)
- Output directories
  - =samples_output=: forward output
  - =enkf_output=: EnKF output
  - =single_cell_output=: output at single cells
* Tags
Tags are used to organize different groups of read and plot
routines. They determine the output-path, the script-path and the path
of to the function definitions of =pskf=. The following tags
exist in =pyshemkf=:
- =analysis=
- =errorplot=
- =forward=
- =gaussianity=
- =monitor=
- =numcomp=
- =presvel=
- =sensitivity=
- =tcon=
- =uindex=
** analysis
tag documentation
** errorplot
tag documentation
** forward
tag documentation
** gaussianity
tag documentation
** monitor
tag documentation
** numcomp
tag documentation
** presvel
tag documentation
** sensitivity
tag documentation
** tcon
tag documentation
** uindex
tag documentation
* Scripts
** endresread.ipy
The script =endresread.ipy= ([[scripts/endresread.ipy]]) is not part of
one of the scripting tags for historical reasons and because it has
the basic preliminary task of reading RMSEs from =SHEMAT-Suite=
output.
** tag-scripts
For each tag, there is a runplot.ipy general script that calls the
read and plot functions from =pskf=. If wanted, numpy arrays and
figures are saved, figures are shown and the script is backuped in the
corresponding =backup= directory.
** templates
A =/scripts/templates= directory will not be part of the
git-repository and can be used for new, not-yet-presentable scripts.
* Module =pskf=
** scripts
The functions in the =scripts= directory
([[/site-packages/pskf/scripts/]]) are tag-specific, i.e. they are meant
to be used by the =runplot.ipy= scripts under a certain tag (for
example =analysis=). Three typical file types exist in one tag
directory:
- =read.py= (Example
  [[/site-packages/pskf/scripts/analysis/read.py]]) contains
  functions for reading the specific SHEMAT-Suite output needed under
  a tag and turning the output into numpy arrays.
- =plot.py= (Example
  [[/site-packages/pskf/scripts/analysis/plot.py]]) contains
  functions for plotting the numpy arrays read in under =read.py=.
- =arrays.py= or =variables.py= (Example
  [[/site-packages/pskf/scripts/analysis/arrays.py]]) contain useful
  tag-specific variables and arrays. One example is the tag name
  itself.
** tools
The =tools= directory ([[/site-packages/pskf/tools/]]) contains general
functions (opposed to the tag-specific functions in =scripts=).
*** plot
General variables and functions related to plotting.
**** plotarrays
Important collection of dates, letters, number of runs and number of
observations for different EnKF runs. According to this information,
specifiers for the different output are defined and standardized.
**** plotfunctions
Plotting functions for handling vtk-input, grid properties, colormaps,
colorbars, scatterplots, hdf (not yet fully tested).
**** specs
Utility functions for reading grid properties from SHEMAT-Suite output
files in SHEMAT-Suite output directories. Important functions defining
the specifiers used to standardize output of the IPython scripts.
*** run
**** pythonmodule
Python-related directory variables
- =python_dir=
- =python_scripts_dir=
- =python_output_dir=
Python-related functions for generating specific directories,
filenames for saving and backups.
**** runmodule
General utility functions for replacing strings, make temporal files,
handling letter endings of specifiers, running shell scripts, reading
and manipulating SHEMAT-Suite input files, compiling SHEMAT, running
matlab, generating lists of SHEMAT-Suite specific files and
directories. Some of these functions are used in scripts to run
SHEMAT-Suite that are not part of the =pyshemkf= repository.
* References
** Rath 2006
Rath, V., Wolf, A., & Bücker, H. M., Joint three-dimensional inversion
of coupled groundwater flow and heat transfer based on automatic
differentiation: sensitivity calculation, verification, and synthetic
examples, Geophysical Journal International, 167(1), 453–466 (2006).
[[http://dx.doi.org/10.1111/j.1365-246x.2006.03074.x]]
** Evensen 2003
Evensen, G., The ensemble kalman filter: theoretical formulation and
practical implementation, Ocean Dynamics, 53(4), 343–367 (2003).
[[http://dx.doi.org/10.1007/s10236-003-0036-9]]
