#+TITLE: PythonDir: Post-Processing SHEMAT-Suite EnKF-Output
#+AUTHOR: Johannes Keller

=PythonDir= is my python environment for post-processing of
=SHEMAT-Suite= ([[*Rath, 2006][Rath, 2006]]) output, including 2D-figures of variables
and parameters, and, most notably, the evaluation and visualization of
RMSE distributions from a number of Ensemble Kalman Filter (EnKF)
synthetic experiments.

-----

* Directory structure
There are three general directories in =PythonDir=: One for output,
one for the Python-scripts and one for the Python module mypackage.
** =/output=
=/output= Directory for output of all kind.
** =/scripts=
IPython scripts.
** =/site-packages/mypackage=
Module with functions ready for use in IPython scripts. For the module
to be loaded by Python, the path has to be added to PYTHONPATH:
#+BEGIN_SRC sh
  export PYTHONPATH=${PYTHONPATH}:/path/to/PythonDir/site-packages
#+END_SRC
* Scripts
** endresread.ipy
The script =endresread.ipy= ([[scripts/endresread.ipy]]) ([[/scripts/]])
([[scripts/]]) ([[/site-packages/mypackage/scripts/]])is not part of one of
the scripting tags for historical reasons and because it has the basic
preliminary task of reading RMSEs from =SHEMAT-Suite= output.
** analysis
** errorplot
** forward
** gaussianity
** monitor
** numcomp
** presvel
** sensitivity
** tcon
** uindex
** templates
A =/scripts/templates= directory will not be part of the
git-repository and can be used for new, not-yet-presentable scripts.
* mypackage
** scripts
The mypackage-functions under the scripts directory usually include
three files:
- =read.py=
- =plot.py=
- =arrays.py=
** tools
*** plot
**** plotarrays
**** plotfunctions
**** specs
*** pp
*** run
**** pythonmodule
**** runmodule
* References
** Rath, 2006
Rath, V., Wolf, A., & Bücker, H. M., Joint three-dimensional inversion
of coupled groundwater flow and heat transfer based on automatic
differentiation: sensitivity calculation, verification, and synthetic
examples, Geophysical Journal International, 167(1), 453–466 (2006).
[[http://dx.doi.org/10.1111/j.1365-246x.2006.03074.x]]
